name: "Diff APK"
description: "View changes between different versions of APK"

inputs:
  github_token:
    description: "Github Token from Secrets"
    required: true
  new_apk:
    description: "Path to the new apk"
    required: true

runs:
  using: "composite"
  steps:
      - name: Get SHA of the branch off point
        shell: bash
        id: old_apk_sha
        run: |-
          git fetch origin main
          echo "old_apk_sha=$(git merge-base --all ${{ github.event.pull_request.head.sha }} origin/main)" >> $GITHUB_OUTPUT

      - name: Logging branch off SHA
        shell: bash
        run: |-
          echo "The branch off SHA: ${{ steps.old_apk_sha.outputs.old_apk_sha }}"

      - name: Download APK
        shell: bash
        run: |-
          if ! [ -x "$(command -v jq)" ]; then
            echo "jq is not installed, installing jq..."
            brew install jq
          fi
          artifactDownloadUrl=$(curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ inputs.github_token }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
          | jq -M -r '.artifacts[] | select(.workflow_run.head_sha == "${{ steps.old_apk_sha.outputs.old_apk_sha }}").archive_download_url')
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ inputs.github_token }}" \
            --create-dirs --output-dir downloads/apk/${{ steps.old_apk_sha.outputs.old_apk_sha }} -o zip\
            -L $artifactDownloadUrl
          IN=downloads/apk/${{ steps.old_apk_sha.outputs.old_apk_sha }}/zip
          unzip -d `dirname $IN` $IN

      - name: Diff APKs
        shell: bash
        id: diff_apk
        run: |-
          if ! [ -x "$(command -v diffuse)" ]; then
            echo "diffuse is not installed, installing diffuse..."
            brew install JakeWharton/repo/diffuse
          fi
          diffuse diff downloads/apk/${{ steps.old_apk_sha.outputs.old_apk_sha }}/*.apk ${{ inputs.new_apk }}
          DIFFUSE_OUTPUT=$(diffuse diff downloads/apk/${{ steps.old_apk_sha.outputs.old_apk_sha }}/*.apk ${{ inputs.new_apk }} | sed -n '/====   DEX   ====/q;p')
          DIFFUSE_OUTPUT="${DIFFUSE_OUTPUT//'%'/'%25'}"
          DIFFUSE_OUTPUT="${DIFFUSE_OUTPUT//$'\n'/'%0A'}"
          DIFFUSE_OUTPUT="${DIFFUSE_OUTPUT//$'\r'/'%0D'}"
          echo "diff_details=$DIFFUSE_OUTPUT" >> $GITHUB_OUTPUT
      
      - name: Get workflow run job url
        shell: bash
        id: get_run_job_url
        run: |-
          workflowRunJobUrl=$(curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.github_token }}" \
          "${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs" \
          | jq -M -r '.jobs[] | select(.name == "${{ github.job }}").html_url')
          echo "workflow_run_job_url::$workflowRunJobUrl" >> $GITHUB_OUTPUT

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: APK Diff Details

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            APK Diff Details
            ```
            ${{ steps.diff_apk.outputs.diff_details }} 
            ```
            More detailed logs can be found here --> ${{ steps.get_run_job_url.outputs.workflow_run_job_url }}
          edit-mode: replace
